# Füge eine Leerzeile zwischen den Eingabeaufforderungen ein
add_newline = true

# Ersetze das "❯" Symbol der Eingabeaufforderung mit "➜"
[character]                            # Der Name des Moduls, welches wir konfigurieren ist "character"
success_symbol = "[➜](bold green)"     # Das "succes_symbol" Segment wird zu "➜" eingestellt und ist "bold green" (fettgedrucktes grün) gefärbt

# Deaktiviere das "package" Modul, damit es aus der Eingabeaufforderung komplett verschwindet
[package]
disabled = true

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"