# install_k3s.yml
---
- hosts: lima_vm
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install dependencies
      apt:
        name: 
          - curl
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Download and install K3s
      shell: curl -sfL https://get.k3s.io | sh -

    - name: Enable and start K3s service
      systemd:
        name: k3s
        enabled: yes
        state: started

    - name: Get Kubeconfig for K3s
      shell: cat /etc/rancher/k3s/k3s.yaml
      register: k3s_kubeconfig

    - name: Save Kubeconfig to local file
      copy:
        content: "{{ k3s_kubeconfig.stdout }}"
        dest: ./k3s.yaml

